### ISSUE TITLE
Adding framework

### ISSUE THREAD

**Issue by Shalini1992** [ClassicalDude/pdfView-Freedraw#2]
Hi ,

I am finding difficulty for adding this framework to my project please guide me how to add using pod install 

Thanks in advance.

**Comment by ClassicalDude** [comment]
This framework does not support CocoaPods. Please follow the installation instructions of the README file. You can either download the xcframework and include it manually in your project, or use a Swift Package.

**Comment by Shalini1992** [comment]
Ok. Thank you for your reply.
