### ISSUE TITLE
Thread 1: "Could not find a storyboard named 'MainPDFView' in bundle NSBundle

### ISSUE THREAD

**Issue by federicaCapobianco** [ClassicalDude/pdfView-Freedraw#6]
I embedded the precompiled framework in Xcode with your instructions and tried to implement it in a swiftUI view this way:

```
import Foundation
import SwiftUI
import UIKit
import PDFKit
import PDFFreedraw

struct PDFKitEditorView: View {
    var url: URL
    var body: some View {
        PDFKitEditorRepresentedView(url)
    }
}

struct PDFKitEditorRepresentedView: UIViewControllerRepresentable {
    let url: URL  
    init(_ url: URL) {
        self.url = url
    }
    
    func makeUIViewController(context: Context) -> UIViewController {
        
        let storyboard = UIStoryboard(name: "MainPDFView", bundle: Bundle.main)
        let controller = storyboard.instantiateViewController(withIdentifier: "PDFViewControllerID")
        
        return controller
    }
    
    func updateUIViewController(_ uiViewController: UIViewController, context: Context) {
        
    }
}
```

What am I missing? I'm getting this error Thread 1: "Could not find a storyboard named 'MainPDFView' in bundle NSBundle
Thank you in advance, I love your framework and really want to get it working

**Comment by Nidhil-stack** [comment]
Yeah, got the same problem but couldn't manage to get it working. Following the thread waiting for Dev's help.

**Comment by ClassicalDude** [comment]
Please see my comment on issue 4: https://github.com/ClassicalDude/pdfView-Freedraw/issues/5#issuecomment-1152994426

Let me know if this resolves the issue.

**Comment by federicaCapobianco** [comment]
Hi, I managed to get it working by changing some IDs here and there in the custom storyboard to match ViewController's ones, it works perfectly now, thank you
